# Generated by Django 5.2.8 on 2025-11-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_id_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient_id',
        ),
    ]
